### ISSUE TITLE
Feature : New permission : Manage others stuff to do reportees

### ISSUE THREAD

**Issue by lspg** [ande3577/redmine-stuff-to-do-plugin#35]
That feature would be nice for admin users

**Comment by cforce** [comment]
I dont understand? Please explain.

**Comment by ande3577** [comment]
This is already supported for an admin user. Go to the user management page and click the _Manage Reportees_ link. This link will only be present if the user has the _View others stuff to do_ permission on at least one project.

I would prefer not to add this as a separate permission, since the natural place for it is on the user's edit page, and this is not available without admin privileges.

**Comment by lspg** [comment]
Ok i understand, and this should be solved with feature https://github.com/ande3577/redmine-stuff-to-do-plugin/issues/36

Closing issue.
