### ISSUE TITLE
Single User?

### ISSUE THREAD

**Issue by nkavian** [ande3577/redmine-stuff-to-do-plugin#51]
No matter what I do, I can't view other user's stuff to do.

"View another user's list" always has just the current logged in user.
Users in the "Filter by" also only ever has the current logged in user.

Redmine version: 2.3.1.stable
Stuff to do version: 0.4.1 (latest version from git)

**Comment by ande3577** [comment]
Sorry for the lack of responsiveness, holidays and work have kind of conspired against my github account as of late.

On a user's account setting there is an an option to either allow a user to manage all reportees or to enable specific reportees for a user.  This is intended to grant a user access to only the stuff to do's of employees who report to them instead of all users. The current implementation is very confusing (see issue #44), so I am planning to address this in a more straight forward manner. Most likely by adding a permission to view all users stuff to do's instead of as an account setting.

**Comment by ande3577** [comment]
This has been changed so that viewing all users stuff to do is now a permission instead of an account option which will hopefully make it more clear how to enable it.
